# Generated by Django 5.2.4 on 2025-07-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.IntegerField()),
                ('respuesta', models.IntegerField()),
                ('respuesta_corecta', models.BooleanField(default=True)),
            ],
        ),
    ]
