# Generated by Django 5.2.4 on 2025-07-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='respuesta',
            new_name='Respuesta',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='respuesta_corecta',
            new_name='Respuesta_corecta',
        ),
    ]
