# Generated by Django 5.2.4 on 2025-07-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_test', '0003_comentariosprofessores_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='test',
        ),
        migrations.RemoveField(
            model_name='resultadointeligencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='ResultadoInteligencia',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
